<WordListScreen>
    FloatLayout:
        id:wordlistfloatlayout
        canvas:
            Rectangle:
                source: 'img/backgroung.png'
                pos: self.pos
                size: self.size
        ScrollView:
            GridLayout: 
                id:scroll_layout 
                cols:1
                size_hint_y: None
                height:self.minimum_height
                row_default_height:"100dp"
                row_force_default:True