<WordsScreen>
    FloatLayout:
        id:Words_floatlayout
        ScrollView:
            pos_hint:{'top':.9,'left':1}
            size_hint:1,.9
            GridLayout: 
                id:Words_scroll_layout 
                cols:1
                size_hint_y: None
                spacing:5,5
                height:self.minimum_height
                row_default_height:"100dp"
                row_force_default:True